#!/usr/bin/env perl

my $dir;
my @dir_arr;
BEGIN {
	use File::Spec::Functions qw( rel2abs catdir );
	use File::Basename qw( dirname basename );
	$dir = dirname( rel2abs( $0 ) );
	while ( 'webUI' ne basename( $dir ) ) {
		$dir = dirname( $dir );
	}
	@dir_arr = map { catdir( $dir, $_ ) } qw( webui.cgi proportal/lib );
}
use lib @dir_arr;

use IMG::Util::Import;
use File::Path qw( make_path );
use File::Spec::Functions;
use File::Basename;

use DBIx::Class::Schema::Loader qw/ make_schema_at /;
use SQL::Translator;
use IMG::Util::DB;
use Getopt::Long;

#	command line options:
#	--constrain    boolean - use the constraints on which tables should be mapped
#	--db   img_core || img_gold || img_sat  (can specify multiple values;
#                                            by default, uses all three databases)

=head2 generate_schema.pl

Generate the database schema using DBIx::Class

Files will be generated in the 'tmp' dir

usage:

generate the DBIx::Class schema:

	perl generate_schema.pl

=cut


my $args = {};

my $opt = GetOptions( $args,
	"db=s@",
	"constrain"
) or script_die( 255, "Error in command line arguments" );

my $abbr = {
	'img_core' => {
		label => 'IMG_Core',
		constraint => sub {
			my @tables = ( @{ core_tables() }, @{ core_synonyms() }, @{ core_views() } );
			my $str = '(' . join( '|', @tables ) . ')';
			return qr{^$str$}i;
		}
	},
	'img_gold' => {
		label => 'IMG_Gold',
		constraint => sub {
			my $h;
			for my $x ( @{ gold_tables() }, @{ core_synonyms() } ) {
				$h->{$x}++;
			}
			my $str = '(' . join( '|', grep { $h->{$_} == 2 } keys %$h ) . ')';

			return qr{^$str$}i;

			return qr/^(cancelled|contact|gold|img)_*/i;
		}
	},
	'img_sat'  => {
		label => 'IMG_Sat',
		constraint => sub {
			# get the intersection of img_sat_tables and core_synonyms
			my $h;
			for my $x ( @{ img_sat_tables() }, @{ core_synonyms() } ) {
				$h->{$x}++;
			}
			my $str = '(' . join( '|', grep { $h->{$_} == 2 } keys %$h ) . ')';
			return qr{^$str$}i;
		}
	}
};


my @dbs;
if ( ! $args->{db} ) {
	@dbs = keys %$abbr;
}
else {
	@dbs = grep { defined $abbr->{$_} } @{$args->{db}};
}

if ( ! @dbs || scalar @dbs == 0 ) {
	script_die( 255, 'No databases specified!' );
}

my $str = 'Running DBIx::Class schema generator ';
if ( defined $args->{constrain} ) {
	$str .= ' in constrained mode ';
}
else {
	$str .= ' in unconstrained mode ';
}
$str .= 'for database(s) ' . join ", ", @dbs;

for my $x ( @dbs ) {
	$abbr->{$x}{conn} = IMG::Util::DB::get_oracle_connection_params({ database => $x });
	create_dbix_class_schema( $x );
}

sub create_dbix_class_schema {
	my $d = shift;

	my $dbic_dir = catdir( $dir, 'tmp' );
	say "Running DBIx::Class schema generator";
	make_path( $dbic_dir . '/DBIC/' );

	say "dir: $dbic_dir";

	if (! -e $dbic_dir . "/DBIC/Schema.pm" ) {
		write_schema_pm( $dbic_dir );
	}

	say 'Running schema generator with args';
	say Dumper $abbr->{$d}{conn};

	my $dbic_args = {
		debug => 1,
		dump_directory => $dbic_dir,
		result_base_class => 'DBIC::Schema',
		naming => { monikers => 'preserve' }
	};
	if ( $args->{constrain} ) {
		$dbic_args->{constraint} = $abbr->{$d}{constraint}->();
	}

	make_schema_at(
		'DBIC::' . $abbr->{$d}{label}, # destination class, e.g. DBIC::IMG_Core::xxx
		$dbic_args,
		[	$abbr->{$d}{conn}{dsn},
			$abbr->{$d}{conn}{username},
			$abbr->{$d}{conn}{password},
			{	RaiseError => 1,
				LongReadLen => 38000,
				LongTruncOk => 1
			}
		],
	);


	say "Finished running DBIC schema generator";
}

sub write_schema_pm {
	my $dbic_dir = shift;
	open( my $fh, ">", catfile( $dbic_dir, 'DBIC', 'Schema.pm' ) ) or die "Could not open output file " . catfile( $dbic_dir, 'DBIC', 'Schema.pm' ) . ": $!";
	print { $fh } join "\n", ( 'package DBIC::Schema;', 'use base "DBIx::Class::Core";', '1;' );
	return;
}

sub core_all {

	return [ qw(
		CONTACT
		PP_DATA_TYPE_VIEW
		PP_DATATYPE
		PP_SUBSET
		TAXON_PROD_VW
		TAXON_STATS_PROD_VW
		VW_GOLD_TAXON
		VW_TAXON
		VW_TAXON_SC
		ASSERTIONCV
		BC_EXT_LINKS
		BIOCYC_CLASS
		BIOCYC_CLASS_PARENTS
		BIOCYC_CLASS_SYNONYMS
		BIOCYC_CLASS_TYPES
		BIOCYC_COMP
		BIOCYC_COMP_EXT_LINKS
		BIOCYC_COMP_SYNONYMS
		BIOCYC_COMP_TYPES
		BIOCYC_ENZRXN
		BIOCYC_ENZRXN_EXT_LINKS
		BIOCYC_ENZRXN_PROSTH_GROUPS
		BIOCYC_ENZRXN_SYNONYMS
		BIOCYC_PATHWAY
		BIOCYC_PATHWAY_COMMENTS
		BIOCYC_PATHWAY_EXT_LINKS
		BIOCYC_PATHWAY_IN_SPECIES
		BIOCYC_PATHWAY_PWY_LINKS
		BIOCYC_PATHWAY_SUB_PWYS
		BIOCYC_PATHWAY_SUPER_PWYS
		BIOCYC_PATHWAY_TAXON_RANGE
		BIOCYC_PATHWAY_TYPES
		BIOCYC_PROTEIN
		BIOCYC_PROTEIN_CATALYZES
		BIOCYC_PROTEIN_EXT_LINKS
		BIOCYC_PROTEIN_IN_SPECIES
		BIOCYC_PROTEIN_SYNONYMS
		BIOCYC_PROTEIN_TYPES
		BIOCYC_REACTION
		BIOCYC_REACTION_EXT_LINKS
		BIOCYC_REACTION_IN_PWYS
		BIOCYC_REACTION_LEFT_HAND
		BIOCYC_REACTION_RIGHT_HAND
		BIOCYC_REACTION_SYNONYMS
		BIOCYC_REACTION_TYPES
		CELL_LOCALIZATION
		COG
		COG_FAMILIES
		COG_FUNCTION
		COG_FUNCTION_OBS
		COG_FUNCTIONS
		COG_FUNCTIONS_OBS
		COG_OBS
		COG_PATHWAY
		COG_PATHWAY_COG_MEMBERS
		COG_SPECIES
		COG2014
		COGFUNC2014
		COMPONENTCV
		COMPOUND
		COMPOUND_ALIASES
		COMPOUND_EXT_LINKS
		CONTACT_IMG_GROUPS
		CONTACT_PROTEXP_PERMISSIONS
		CONTACT_RNA_DATA_PERMISSIONS
		CONTACT_RNAEXP_PERMISSIONS
		CONTACT_SNP_EXP_PERMISSIONS
		CONTACT_TAXON_PERMISSIONS
		DT_ALL_PHYLO_TAXON_STATS
		DT_KO_EC_COG_PFAM
		DT_PHYLO_TAXON_STATS
		EGGNOG_HIERARCHY
		EGGNOG_MD52ID2ONT
		ENV_SAMPLE
		ENV_SAMPLE_ENERGY_SOURCE
		ENV_SAMPLE_GOLD
		ENV_SAMPLE_SEQ_METHOD
		ENZYME
		ENZYME_ENZ_ALIASES
		ENZYME_EXT_LINKS
		ENZYME_PRODUCTS
		ENZYME_SUBSTRATES
		GENE_IMG_FUNCTIONS
		GENE_MYIMG_ENZYMES
		GENE_MYIMG_FUNCTIONS
		GENE_MYIMG_GROUPS
		GENE_MYIMG_TERMS
		GENE_SNP
		GENOME_PROPERTY
		GENOME_PROPERTY_PARENTS
		GO_GRAPH_PATH
		GO_TERM
		GO_TERM_PARENTS
		GO_TERM_SYNONYMS
		GOLD_ANALYSIS_PROJECT
		GOLD_ANALYSIS_PROJECT_LOOKUP2
		GOLD_ANALYSIS_PROJECT_USERS
		GOLD_SEQUENCING_PROJECT
		GOLD_SP_CELL_ARRANGEMENT
		GOLD_SP_COLLABORATOR
		GOLD_SP_DISEASE
		GOLD_SP_ENERGY_SOURCE
		GOLD_SP_GENOME_PUBLICATIONS
		GOLD_SP_HABITAT
		GOLD_SP_METABOLISM
		GOLD_SP_PHENOTYPE
		GOLD_SP_RELEVANCE
		GOLD_SP_SEQ_CENTER
		GOLD_SP_SEQ_METHOD
		GOLD_SP_STUDY_GOLD_ID
		IMAGE_ROI
		IMAGE_ROI_COMPOUNDS
		IMAGE_ROI_ENZYMES
		IMAGE_ROI_KO_TERMS
		IMAGE_ROI_REACTIONS
		IMG_BUILD_HISTORY
		IMG_COMPOUND
		IMG_COMPOUND_ACTIVITY
		IMG_COMPOUND_ALIASES
		IMG_COMPOUND_EXT_LINKS
		IMG_COMPOUND_KEGG_COMPOUNDS
		IMG_COMPOUND_MESHD_TREE
		IMG_GOLD_PHENOTYPE
		IMG_GROUP
		IMG_GROUP_NEWS
		IMG_JOB_PARAMCV
		IMG_JOB_STATUSCV
		IMG_JOB_TYPECV
		IMG_PARTS_LIST
		IMG_PARTS_LIST_IMG_TERMS
		IMG_PATHWAY
		IMG_PATHWAY_ASSERTIONS
		IMG_PATHWAY_C_COMPONENTS
		IMG_PATHWAY_REACTIONS
		IMG_PATHWAY_T_COMPONENTS
		IMG_PATHWAY_TAXONS
		IMG_REACTION
		IMG_REACTION_ASSOC_NETWORKS
		IMG_REACTION_ASSOC_PATHS
		IMG_REACTION_ASSOC_RXNS
		IMG_REACTION_C_COMPONENTS
		IMG_REACTION_CATALYSTS
		IMG_REACTION_EXT_LINKS
		IMG_REACTION_T_COMPONENTS
		IMG_TERM
		IMG_TERM_CHILDREN
		IMG_TERM_ENZYMES
		IMG_TERM_GRAPH_PATH
		IMG_TERM_SYNONYMS
		IMGTERMCV
		INTERPRO
		INTERPRO_GO_TERMS
		KEGG_GENE
		KEGG_GENE_KO_TERMS
		KEGG_GENE_NCBI_GENE_IDS
		KEGG_GENE_NCBI_GI_NUMS
		KEGG_GENE_UNIPROT_IDS
		KEGG_MODULE
		KEGG_MODULE_COMPOUNDS
		KEGG_MODULE_KO_TERMS
		KEGG_MODULE_REACTIONS
		KEGG_PATHWAY
		KEGG_PATHWAY_MODULES
		KEGG_PATHWAY_RELATED_PATHWAYS
		KM_IMAGE_ROI
		KM_IMAGE_ROI_KO_TERMS
		KO_TERM
		KO_TERM_CLASSES
		KO_TERM_COGS
		KO_TERM_ENZYMES
		KO_TERM_GO_IDS
		KO_TERM_MODULES
		KO_TERM_PATHWAYS
		KO_TERM_REACTIONS
		KO_TERM_TC_FAMILIES
		KOG
		KOG_FAMILIES
		KOG_FUNCTION
		KOG_FUNCTIONS
		KOG_PATHWAY
		KOG_PATHWAY_KOG_MEMBERS
		MESH_DTREE
		METH_EXP
		METH_EXPERIMENT
		METH_EXPERIMENT_EXT_LINKS
		METH_EXPERIMENT_PUBLICATIONS
		METH_FUNCTION_COVERAGE
		METH_MODIFICATION
		METH_MOTIF
		METH_MOTIF_SUMMARY
		METH_SAMPLE
		METH_STATS
		MPW_PGL_COMPOUND
		MPW_PGL_GENE_GROUP
		MPW_PGL_PATHWAY
		MPW_PGL_PATHWAY_REACTION
		MPW_PGL_PROTEIN_GROUP
		MPW_PGL_REACTION
		MPW_PGL_REACTION_COMPOUNDS
		MPW_PGL_TAXONOMY
		MS_EXPERIMENT
		MS_EXPERIMENT_EXT_LINKS
		MS_EXPERIMENT_PUBLICATIONS
		MS_EXPERIMENT_SOP
		MS_PEPTIDE
		MS_PEPTIDE_OLD
		MS_PROTEIN
		MS_PROTEIN_IMG_GENES
		MS_PROTEIN_IMG_GENES_OLD
		MS_PROTEIN_OLD
		MS_SAMPLE
		MS_SAMPLE_EXT_LINKS
		MS_SAMPLE_SOP
		MYGENE
		MYGENE_IMG_GROUPS
		MYGENE_TERMS
		MYIMG_BIO_CLUSTER_NP
		MYIMG_JOB
		MYIMG_JOB_PARAMETERS
		MYIMG_JOB_USERS
		NATURAL_PRODUCT
		NP_ACTIVITY_CV
		NP_BIOSYNTHESIS_SOURCE
		NP_SIMILARITY
		PATHWAY_NETWORK
		PATHWAY_NETWORK_C_COMPONENTS
		PATHWAY_NETWORK_IMG_PATHWAYS
		PATHWAY_NETWORK_PARENTS
		PATHWAY_NETWORK_PARTS_LISTS
		PATHWAY_NETWORK_T_COMPONENTS
		PATHWAY_NETWORK_TAXONS
		PFAM_CLAN
		PFAM_CLAN_PFAM_FAMILIES
		PFAM_FAMILY
		PFAM_FAMILY_COGS
		PFAM_FAMILY_EXT_LINKS
		PFAM_FAMILY_FAMILIES
		PFAM_FAMILY_GENOME_PROPERTIES
		PHENOTYPE_RULE
		PHENOTYPE_RULE_TAXONS
		PROJECT_INFO
		PROJECT_INFO_BODY_SITES
		PROJECT_INFO_DATA_LINKS
		PROJECT_INFO_DISEASES
		PROJECT_INFO_ECOTYPES
		PROJECT_INFO_GOLD
		PROJECT_INFO_PHENOTYPES
		PROJECT_INFO_PROJECT_RELEVANCE
		PROJECT_INFO_RELEVANCES
		PROPERTY_STEP
		PROPERTY_STEP_EVIDENCES
		PUBLIC_SET
		REACTION
		REACTION_COMPOUNDS
		REACTION_ENZYMES
		REACTION_EXT_LINKS
		RNASEQ_DATASET
		RNASEQ_DATASET_STATS
		RNASEQ_EXPERIMENT
		RNASEQ_EXPERIMENT_EXT_LINKS
		RNASEQ_EXPERIMENT_PUBS
		RNASEQ_EXPERIMENT_SOP
		RNASEQ_EXPERIMENT_STATS
		RNASEQ_EXPRESSION
		RNASEQ_EXPRESSION_NEW
		RNASEQ_SAMPLE
		RNASEQ_SAMPLE_EXT_LINKS
		RNASEQ_SAMPLE_SOP
		SEED_FUNCTIONAL_ROLE
		STATUSCV
		SUBMISSION
		SUBMISSION_DATA_FILES
		SUBMISSION_IMG_CONTACTS
		SUBMISSION_SAMPLES
		SUBMISSION_STATUSCV
		TAXON_COG_COUNT
		TAXON_EC_COUNT
		TAXON_KO_COUNT
		TAXON_PFAM_COUNT
		TAXON_TIGR_COUNT
		TAXON_UPDATE_REQUEST
		TC_FAMILY
		TC_FAMILY_COGS
		TC_FAMILY_GO_TERMS
		TC_FAMILY_IMG_TERMS
		TC_FAMILY_PFAMS
		TC_FAMILY_PFAMS_IAIN
		TC_FAMILY_TFAMS
		TIGR_ROLE
		TIGRFAM
		TIGRFAM_ENZYMES
		TIGRFAM_GENOME_PROPERTIES
		TIGRFAM_ROLES
		ACCESSION_TYPES
		ALT_TRANSCRIPT
		ANI_CLIQUE
		ANI_CLIQUE_MEMBERS
		ANI_INTER_CLIQUE
		ANI_NEW_TAXONS
		ANI_OLD_TAXONS
		ASSEMBLY
		BBH_CLUSTER
		BBH_CLUSTER_FAMILIES
		BBH_CLUSTER_MEMBER_GENES
		BC_TYPE
		BIN
		BIN_METHOD
		BIN_SCAFFOLDS
		BIN_STATS
		BIO_CLUSTER
		BIO_CLUSTER_DATA
		BIO_CLUSTER_DATA_NEW
		BIO_CLUSTER_FEATURES
		BIO_CLUSTER_FEATURES_NEW
		BIO_CLUSTER_NEW
		CASSETTE_BOX
		CASSETTE_BOX_BBH
		CASSETTE_BOX_BBH_XLOGS
		CASSETTE_BOX_CASSETTES_BBH
		CASSETTE_BOX_CASSETTES_COG
		CASSETTE_BOX_CASSETTES_PFAM
		CASSETTE_BOX_COG
		CASSETTE_BOX_COG_XLOGS
		CASSETTE_BOX_PFAM
		CASSETTE_BOX_PFAM_XLOGS
		CDS_MAPPING_SUMMARY
		CONCURRENCYTEST
		COPY
		COPY_ER_FINAL
		COPY_MER_ALL
		COPY_MER_FINAL
		COPY_MER_PHASE1
		DB_SOURCE
		DT_BC2EC
		DT_COG
		DT_COG_STATS
		DT_DB_STATUS
		DT_FUNC_COMBO_4ITERMS
		DT_FUNC_COMBO_4KO
		DT_FUNC_COMBO_GENES_4ITERMS
		DT_FUNC_COMBO_GENES_4KO
		DT_FUNCS_OBS
		DT_GENE_KO_MODULE_PWYS
		DT_HT_HITS
		DT_IMG_GENE_PROT_PEP_SAMPLE
		DT_IMG_TERM_PATH
		DT_INTERGENIC
		DT_KO
		DT_KO_TERM_COMBO_STATS
		DT_KO_TERM_PARALOG_STATS
		DT_KOG_STATS
		DT_MVC_TAXONOMY
		DT_PFAM
		DT_PHYLODIST_NEW_TAXONS
		DT_PHYLUM_DIST_GENES
		DT_PHYLUM_DIST_STATS
		DT_SCOG_GENES
		DT_SCOGS
		DT_TAXON_BBH_CLUSTER
		DT_TAXON_KMODULE_MCR
		DT_TAXON_NODE_LITE
		DT_TEMP
		DT_TEMP_2
		DT_TFAM
		DT_VIRAL_CLUSTERS
		DT_VIRAL_HOST_ASSIGNMENT
		DT_VIRAL_SPACER
		DT_VIRALS_FROM_METAG
		ENV_SAMPLE_OBSOLETE
		ENV_SAMPLE_OLD
		ENV_SAMPLE_TEMP
		GENE
		GENE_ALIASES
		GENE_ALL_FUSION_COMPONENTS
		GENE_BIOCYC_RXNS
		GENE_CANDIDATE_KO_TERMS
		GENE_CASSETTE
		GENE_CASSETTE_GENES
		GENE_CASSETTE_PANFOLDS
		GENE_COG_GROUPS
		GENE_DNA_UBLAST
		GENE_EGGNOGS
		GENE_ENZYMES
		GENE_ESSENTIAL_GENES
		GENE_EXCEPTIONS
		GENE_EXT_LINKS
		GENE_FEATURE_TAGS
		GENE_FRAG_COORDS
		GENE_FUSION_COMPONENTS
		GENE_GO_TERMS
		GENE_IMG_INTERPRO_HITS
		GENE_KO_ENZYMES
		GENE_KO_TERMS
		GENE_KOG_GROUPS
		GENE_LIPO_PEPTIDES
		GENE_MAPPING
		GENE_MD5DNA
		GENE_NOTES
		GENE_ORTHOLOGS
		GENE_PANGENE_COMPOSITION
		GENE_PARALOGS
		GENE_PDB_XREFS
		GENE_PFAM_FAMILIES
		GENE_PFAM_FAMILIES_OLD
		GENE_PREV_VERSIONS
		GENE_REPLACEMENTS
		GENE_RNA_CLUSTERS
		GENE_SEED_NAMES
		GENE_SIG_PEPTIDES
		GENE_SWISSPROT_NAMES
		GENE_TC_FAMILIES
		GENE_TIGRFAMS
		GENE_TMHMM_HITS
		GENE_XREF_FAMILIES
		GOLD_ACC_COUNTS
		IMG_ACC_COUNTS
		IMG_BUILD
		IMG_CLUSTER
		IMG_CLUSTER_FAMILIES
		IMG_CLUSTER_MEMBER_GENES
		IMG_CONTENT_HISTORY
		IMG_ORF_TYPE
		INSUR_CUST_LTV_SAMPLE
		KP_LINKS
		KP_TAXONS
		KP_TEMP
		KP_TMP
		MAP_TAXON_PAIRS
		MER_INFILE_TAXON_0918
		MERFS_GENE_MAPPING
		MV_BIO_CLUSTER_SEQLEN
		MV_BIO_CLUSTER_STAT
		MV_METACYC_STATS
		MV_TAXON_COG_STAT
		MV_TAXON_EC_STAT
		MV_TAXON_IPR_STAT
		MV_TAXON_ITERMS_STAT
		MV_TAXON_KEGG_CAT_STAT
		MV_TAXON_KEGG_MOD_STAT
		MV_TAXON_KEGG_STAT
		MV_TAXON_KO_STAT
		MV_TAXON_KOG_STAT
		MV_TAXON_METACYC_STAT
		MV_TAXON_PFAM_STAT
		MV_TAXON_TC_STAT
		MV_TAXON_TFAM_STAT
		NCBI_PROJECTS_LIST_BY_APID
		NCBI_PROJECTS_LIST_BY_GOLD_ID
		PANGENOME_COUNT
		PANGENOME_COUNT_GENES
		PARALOG_GROUP
		PARALOG_GROUP_GENES
		POSITIONAL_CLUSTER
		POSITIONAL_CLUSTER_GENES
		PROMOTEMYGENES_1014
		RECOMPUTE_TAXONS
		REFSEQ_UNIPROT
		REM_DUP_BC
		REPAIR_16S_GENOMES
		REVISED_COG_CLUSTER_COUNT
		REVISED_COG_COUNT_COMBINED
		RNA_CLUSTER
		SCAFFOLD
		SCAFFOLD_EXT_LINKS
		SCAFFOLD_INTERGENIC
		SCAFFOLD_MISC_BINDINGS
		SCAFFOLD_MISC_FEATURES
		SCAFFOLD_NOTES
		SCAFFOLD_NX_FEATURE
		SCAFFOLD_PANFOLD_COMPOSITION
		SCAFFOLD_REPEATS
		SCAFFOLD_SIG_PEPTIDES
		SCAFFOLD_STATS
		TAXON
		TAXON_AA_STATS
		TAXON_ANI_MATRIX
		TAXON_ANI_NULL_PAIRS
		TAXON_CODON_STATS
		TAXON_CRISPR_DETAILS
		TAXON_CRISPR_SUMMARY
		TAXON_DIST_MATRIX
		TAXON_EXT_LINKS
		TAXON_GENE_PREFIX
		TAXON_NODE_LITE
		TAXON_PANGENOME_COMPOSITION
		TAXON_QUALITY_MEASURE
		TAXON_RELATED_TAXONS
		TAXON_REPLACEMENTS
		TAXON_SCAF_PREFIX
		TAXON_STATS
		TAXON_STATS_MERFS
		TDM_NEW_TAXONS
		TDM_OLD_TAXONS
		TEMP_GENE_NAMES
		TEST_KP
		TMP_GENE_ENZYMES
		TMP_PFAM_DOMAIN
		TMP_PFAM_PHYLUM
		TMP_TAXON_PFAM
		UNMAPPED_GENES_ARCHIVE
		VIRALTAXONS
		YESNOCV
	) ];
}

sub core_tables {

	return [ qw(
		ACCESSION_TYPES
		ALT_TRANSCRIPT
		ANI_CLIQUE
		ANI_CLIQUE_MEMBERS
		ANI_INTER_CLIQUE
		ANI_NEW_TAXONS
		ANI_OLD_TAXONS
		ASSEMBLY
		BBH_CLUSTER
		BBH_CLUSTER_FAMILIES
		BBH_CLUSTER_MEMBER_GENES
		BC_TYPE
		BIN
		BIN_METHOD
		BIN_SCAFFOLDS
		BIN_STATS
		BIO_CLUSTER
		BIO_CLUSTER_DATA
		BIO_CLUSTER_DATA_NEW
		BIO_CLUSTER_FEATURES
		BIO_CLUSTER_FEATURES_NEW
		BIO_CLUSTER_NEW
		CASSETTE_BOX
		CASSETTE_BOX_BBH
		CASSETTE_BOX_BBH_XLOGS
		CASSETTE_BOX_CASSETTES_BBH
		CASSETTE_BOX_CASSETTES_COG
		CASSETTE_BOX_CASSETTES_PFAM
		CASSETTE_BOX_COG
		CASSETTE_BOX_COG_XLOGS
		CASSETTE_BOX_PFAM
		CASSETTE_BOX_PFAM_XLOGS
		CDS_MAPPING_SUMMARY
		CONCURRENCYTEST
		COPY
		COPY_ER_FINAL
		COPY_MER_ALL
		COPY_MER_FINAL
		COPY_MER_PHASE1
		DB_SOURCE
		DELETE_GENES
		DELETE_SCAFFOLDS
		DELETE_TAXONS
		DT_BC2EC
		DT_COG
		DT_COG_STATS
		DT_DB_STATUS
		DT_FUNC_COMBO_4ITERMS
		DT_FUNC_COMBO_4KO
		DT_FUNC_COMBO_GENES_4ITERMS
		DT_FUNC_COMBO_GENES_4KO
		DT_FUNCS_OBS
		DT_GENE_KO_MODULE_PWYS
		DT_HT_HITS
		DT_IMG_GENE_PROT_PEP_SAMPLE
		DT_IMG_TERM_PATH
		DT_INTERGENIC
		DT_KO
		DT_KO_TERM_COMBO_STATS
		DT_KO_TERM_PARALOG_STATS
		DT_KOG_STATS
		DT_MVC_TAXONOMY
		DT_PFAM
		DT_PHYLODIST_NEW_TAXONS
		DT_PHYLUM_DIST_GENES
		DT_PHYLUM_DIST_STATS
		DT_SCOG_GENES
		DT_SCOGS
		DT_TAXON_BBH_CLUSTER
		DT_TAXON_KMODULE_MCR
		DT_TAXON_NODE_LITE
		DT_TEMP
		DT_TEMP_2
		DT_TFAM
		DT_VIRAL_CLUSTERS
		DT_VIRAL_HOST_ASSIGNMENT
		DT_VIRAL_SPACER
		DT_VIRALS_FROM_METAG
		ENV_SAMPLE_OBSOLETE
		ENV_SAMPLE_OLD
		ENV_SAMPLE_TEMP
		GENE
		GENE_ALIASES
		GENE_ALL_FUSION_COMPONENTS
		GENE_BIOCYC_RXNS
		GENE_CANDIDATE_KO_TERMS
		GENE_CASSETTE
		GENE_CASSETTE_GENES
		GENE_CASSETTE_PANFOLDS
		GENE_COG_GROUPS
		GENE_DNA_UBLAST
		GENE_EGGNOGS
		GENE_ENZYMES
		GENE_ESSENTIAL_GENES
		GENE_EXCEPTIONS
		GENE_EXT_LINKS
		GENE_FEATURE_TAGS
		GENE_FRAG_COORDS
		GENE_FUSION_COMPONENTS
		GENE_GO_TERMS
		GENE_IMG_INTERPRO_HITS
		GENE_KO_ENZYMES
		GENE_KO_TERMS
		GENE_KOG_GROUPS
		GENE_LIPO_PEPTIDES
		GENE_MAPPING
		GENE_MD5DNA
		GENE_NOTES
		GENE_ORTHOLOGS
		GENE_PANGENE_COMPOSITION
		GENE_PARALOGS
		GENE_PDB_XREFS
		GENE_PFAM_FAMILIES
		GENE_PFAM_FAMILIES_OLD
		GENE_PREV_VERSIONS
		GENE_REPLACEMENTS
		GENE_RNA_CLUSTERS
		GENE_SEED_NAMES
		GENE_SIG_PEPTIDES
		GENE_SWISSPROT_NAMES
		GENE_TC_FAMILIES
		GENE_TIGRFAMS
		GENE_TMHMM_HITS
		GENE_XREF_FAMILIES
		GOLD_ACC_COUNTS
		GTT_FUNC_ID
		GTT_FUNC_ID1
		GTT_FUNC_ID2
		GTT_FUNC_ID3
		GTT_FUNCTION_GENE
		GTT_KEN
		GTT_KEN2
		GTT_KP
		GTT_NUM_ID
		GTT_NUM_ID1
		GTT_NUM_ID2
		GTT_NUM_ID3
		GTT_TAXON_OID
		IMG_ACC_COUNTS
		IMG_BUILD
		IMG_CLUSTER
		IMG_CLUSTER_FAMILIES
		IMG_CLUSTER_MEMBER_GENES
		IMG_CONTENT_HISTORY
		IMG_ORF_TYPE
		INSUR_CUST_LTV_SAMPLE
		KP_LINKS
		KP_TAXONS
		KP_TEMP
		KP_TMP
		MAP_TAXON_PAIRS
		MER_INFILE_TAXON_0918
		MERFS_GENE_MAPPING
		MV_BIO_CLUSTER_SEQLEN
		MV_BIO_CLUSTER_STAT
		MV_METACYC_STATS
		MV_TAXON_COG_STAT
		MV_TAXON_EC_STAT
		MV_TAXON_IPR_STAT
		MV_TAXON_ITERMS_STAT
		MV_TAXON_KEGG_CAT_STAT
		MV_TAXON_KEGG_MOD_STAT
		MV_TAXON_KEGG_STAT
		MV_TAXON_KO_STAT
		MV_TAXON_KOG_STAT
		MV_TAXON_METACYC_STAT
		MV_TAXON_PFAM_STAT
		MV_TAXON_TC_STAT
		MV_TAXON_TFAM_STAT
		NCBI_PROJECTS_LIST_BY_APID
		NCBI_PROJECTS_LIST_BY_GOLD_ID
		NEW_REPLACE_TAXONS
		NEW_TAXONS
		NEW_TAXONS_0201
		NEW_TAXONS_0405
		NEW_TAXONS_BATCH
		NEW_TAXONS_MER_AVA
		NEW_TAXONS_MINI_1130
		NEW_TAXONS_PFAM_FIX
		NEW_TAXONS_PFAM30
		NEW_TAXONS_PFAMKOTFAM_REDO
		NEW_TAXONS_PFAMV29KEGG77_1
		NEW_TAXONS_TFAM_FIX
		OLD_TAXONS
		PANGENOME_COUNT
		PANGENOME_COUNT_GENES
		PARALOG_GROUP
		PARALOG_GROUP_GENES
		POSITIONAL_CLUSTER
		POSITIONAL_CLUSTER_GENES
		PROMOTEMYGENES_1014
		RECOMPUTE_TAXONS
		REFSEQ_UNIPROT
		REM_DUP_BC
		REPAIR_16S_GENOMES
		REVISED_COG_CLUSTER_COUNT
		REVISED_COG_COUNT_COMBINED
		RNA_CLUSTER
		SCAFFOLD
		SCAFFOLD_EXT_LINKS
		SCAFFOLD_INTERGENIC
		SCAFFOLD_MISC_BINDINGS
		SCAFFOLD_MISC_FEATURES
		SCAFFOLD_NOTES
		SCAFFOLD_NX_FEATURE
		SCAFFOLD_PANFOLD_COMPOSITION
		SCAFFOLD_REPEATS
		SCAFFOLD_SIG_PEPTIDES
		SCAFFOLD_STATS
		T1
		T2
		T3
		TAXON
		TAXON_AA_STATS
		TAXON_ANI_MATRIX
		TAXON_ANI_NULL_PAIRS
		TAXON_CODON_STATS
		TAXON_CRISPR_DETAILS
		TAXON_CRISPR_SUMMARY
		TAXON_DIST_MATRIX
		TAXON_EXT_LINKS
		TAXON_GENE_PREFIX
		TAXON_NODE_LITE
		TAXON_PANGENOME_COMPOSITION
		TAXON_QUALITY_MEASURE
		TAXON_RELATED_TAXONS
		TAXON_REPLACEMENTS
		TAXON_SCAF_PREFIX
		TAXON_STATS
		TAXON_STATS_MERFS
		TDM_NEW_TAXONS
		TDM_OLD_TAXONS
		TEMP_GENE_NAMES
		TEST_KP
		TMP_GENE_ENZYMES
		TMP_PFAM_DOMAIN
		TMP_PFAM_PHYLUM
		TMP_TAXON_PFAM
		UNMAPPED_GENES_ARCHIVE
		VIRALTAXONS
		YESNOCV
	) ];
}

sub core_views {

	return [ qw(
		CONTACT
		PP_DATA_TYPE_VIEW
		REPLACED_METAGENOMES
		TAXON_PROD_VW
		TAXON_STATS_PROD_VW
		VW_GOLD_TAXON
		VW_TAXON
		VW_TAXON_SC
	) ];

}

sub core_synonyms {

	return [ qw(
		ASSERTIONCV
		BC_EXT_LINKS
		BIOCYC_CLASS
		BIOCYC_CLASS_PARENTS
		BIOCYC_CLASS_SYNONYMS
		BIOCYC_CLASS_TYPES
		BIOCYC_COMP
		BIOCYC_COMP_EXT_LINKS
		BIOCYC_COMP_SYNONYMS
		BIOCYC_COMP_TYPES
		BIOCYC_ENZRXN
		BIOCYC_ENZRXN_EXT_LINKS
		BIOCYC_ENZRXN_PROSTH_GROUPS
		BIOCYC_ENZRXN_SYNONYMS
		BIOCYC_PATHWAY
		BIOCYC_PATHWAY_COMMENTS
		BIOCYC_PATHWAY_EXT_LINKS
		BIOCYC_PATHWAY_IN_SPECIES
		BIOCYC_PATHWAY_PWY_LINKS
		BIOCYC_PATHWAY_SUB_PWYS
		BIOCYC_PATHWAY_SUPER_PWYS
		BIOCYC_PATHWAY_TAXON_RANGE
		BIOCYC_PATHWAY_TYPES
		BIOCYC_PROTEIN
		BIOCYC_PROTEIN_CATALYZES
		BIOCYC_PROTEIN_EXT_LINKS
		BIOCYC_PROTEIN_IN_SPECIES
		BIOCYC_PROTEIN_SYNONYMS
		BIOCYC_PROTEIN_TYPES
		BIOCYC_REACTION
		BIOCYC_REACTION_EXT_LINKS
		BIOCYC_REACTION_IN_PWYS
		BIOCYC_REACTION_LEFT_HAND
		BIOCYC_REACTION_RIGHT_HAND
		BIOCYC_REACTION_SYNONYMS
		BIOCYC_REACTION_TYPES
		CANCELLED_USER
		CELL_LOCALIZATION
		COG
		COG_FAMILIES
		COG_FUNCTION
		COG_FUNCTION_OBS
		COG_FUNCTIONS
		COG_FUNCTIONS_OBS
		COG_OBS
		COG_PATHWAY
		COG_PATHWAY_COG_MEMBERS
		COG_SPECIES
		COG2014
		COGFUNC2014
		COMPONENTCV
		COMPOUND
		COMPOUND_ALIASES
		COMPOUND_EXT_LINKS
		CONTACT_IMG_GROUPS
		CONTACT_PROTEXP_PERMISSIONS
		CONTACT_RNA_DATA_PERMISSIONS
		CONTACT_RNAEXP_PERMISSIONS
		CONTACT_SNP_EXP_PERMISSIONS
		CONTACT_TAXON_PERMISSIONS
		DT_ALL_PHYLO_TAXON_STATS
		DT_KO_EC_COG_PFAM
		DT_PHYLO_TAXON_STATS
		EGGNOG_HIERARCHY
		EGGNOG_MD52ID2ONT
		ENV_SAMPLE
		ENV_SAMPLE_ENERGY_SOURCE
		ENV_SAMPLE_GOLD
		ENV_SAMPLE_SEQ_METHOD
		ENZYME
		ENZYME_ENZ_ALIASES
		ENZYME_EXT_LINKS
		ENZYME_PRODUCTS
		ENZYME_SUBSTRATES
		GENE_IMG_FUNCTIONS
		GENE_MYIMG_ENZYMES
		GENE_MYIMG_FUNCTIONS
		GENE_MYIMG_GROUPS
		GENE_MYIMG_TERMS
		GENE_SNP
		GENOME_PROPERTY
		GENOME_PROPERTY_PARENTS
		GO_GRAPH_PATH
		GO_TERM
		GO_TERM_PARENTS
		GO_TERM_SYNONYMS
		GOLD_ANALYSIS_PROJECT
		GOLD_ANALYSIS_PROJECT_LOOKUP2
		GOLD_ANALYSIS_PROJECT_USERS
		GOLD_SEQUENCING_PROJECT
		GOLD_SP_CELL_ARRANGEMENT
		GOLD_SP_COLLABORATOR
		GOLD_SP_DISEASE
		GOLD_SP_ENERGY_SOURCE
		GOLD_SP_GENOME_PUBLICATIONS
		GOLD_SP_HABITAT
		GOLD_SP_METABOLISM
		GOLD_SP_PHENOTYPE
		GOLD_SP_RELEVANCE
		GOLD_SP_SEQ_CENTER
		GOLD_SP_SEQ_METHOD
		GOLD_SP_STUDY_GOLD_ID
		IMAGE_ROI
		IMAGE_ROI_COMPOUNDS
		IMAGE_ROI_ENZYMES
		IMAGE_ROI_KO_TERMS
		IMAGE_ROI_REACTIONS
		IMG_BUILD_HISTORY
		IMG_COMPOUND
		IMG_COMPOUND_ACTIVITY
		IMG_COMPOUND_ALIASES
		IMG_COMPOUND_EXT_LINKS
		IMG_COMPOUND_KEGG_COMPOUNDS
		IMG_COMPOUND_MESHD_TREE
		IMG_GOLD_PHENOTYPE
		IMG_GROUP
		IMG_GROUP_NEWS
		IMG_JOB_PARAMCV
		IMG_JOB_STATUSCV
		IMG_JOB_TYPECV
		IMG_PARTS_LIST
		IMG_PARTS_LIST_IMG_TERMS
		IMG_PATHWAY
		IMG_PATHWAY_ASSERTIONS
		IMG_PATHWAY_C_COMPONENTS
		IMG_PATHWAY_REACTIONS
		IMG_PATHWAY_T_COMPONENTS
		IMG_PATHWAY_TAXONS
		IMG_REACTION
		IMG_REACTION_ASSOC_NETWORKS
		IMG_REACTION_ASSOC_PATHS
		IMG_REACTION_ASSOC_RXNS
		IMG_REACTION_C_COMPONENTS
		IMG_REACTION_CATALYSTS
		IMG_REACTION_EXT_LINKS
		IMG_REACTION_T_COMPONENTS
		IMG_TERM
		IMG_TERM_CHILDREN
		IMG_TERM_ENZYMES
		IMG_TERM_GRAPH_PATH
		IMG_TERM_SYNONYMS
		IMGTERMCV
		INTERPRO
		INTERPRO_GO_TERMS
		KEGG_GENE
		KEGG_GENE_KO_TERMS
		KEGG_GENE_NCBI_GENE_IDS
		KEGG_GENE_NCBI_GI_NUMS
		KEGG_GENE_UNIPROT_IDS
		KEGG_MODULE
		KEGG_MODULE_COMPOUNDS
		KEGG_MODULE_KO_TERMS
		KEGG_MODULE_REACTIONS
		KEGG_PATHWAY
		KEGG_PATHWAY_MODULES
		KEGG_PATHWAY_RELATED_PATHWAYS
		KM_IMAGE_ROI
		KM_IMAGE_ROI_KO_TERMS
		KO_TERM
		KO_TERM_CLASSES
		KO_TERM_COGS
		KO_TERM_ENZYMES
		KO_TERM_GO_IDS
		KO_TERM_MODULES
		KO_TERM_PATHWAYS
		KO_TERM_REACTIONS
		KO_TERM_TC_FAMILIES
		KOG
		KOG_FAMILIES
		KOG_FUNCTION
		KOG_FUNCTIONS
		KOG_PATHWAY
		KOG_PATHWAY_KOG_MEMBERS
		MESH_DTREE
		METH_EXP
		METH_EXPERIMENT
		METH_EXPERIMENT_EXT_LINKS
		METH_EXPERIMENT_PUBLICATIONS
		METH_FUNCTION_COVERAGE
		METH_MODIFICATION
		METH_MOTIF
		METH_MOTIF_SUMMARY
		METH_SAMPLE
		METH_STATS
		MPW_PGL_COMPOUND
		MPW_PGL_GENE_GROUP
		MPW_PGL_PATHWAY
		MPW_PGL_PATHWAY_REACTION
		MPW_PGL_PROTEIN_GROUP
		MPW_PGL_REACTION
		MPW_PGL_REACTION_COMPOUNDS
		MPW_PGL_TAXONOMY
		MS_EXPERIMENT
		MS_EXPERIMENT_EXT_LINKS
		MS_EXPERIMENT_PUBLICATIONS
		MS_EXPERIMENT_SOP
		MS_PEPTIDE
		MS_PEPTIDE_OLD
		MS_PROTEIN
		MS_PROTEIN_IMG_GENES
		MS_PROTEIN_IMG_GENES_OLD
		MS_PROTEIN_OLD
		MS_SAMPLE
		MS_SAMPLE_EXT_LINKS
		MS_SAMPLE_SOP
		MYGENE
		MYGENE_IMG_GROUPS
		MYGENE_TERMS
		MYIMG_BIO_CLUSTER_NP
		MYIMG_JOB
		MYIMG_JOB_PARAMETERS
		MYIMG_JOB_USERS
		NATURAL_PRODUCT
		NP_ACTIVITY_CV
		NP_BIOSYNTHESIS_SOURCE
		NP_SIMILARITY
		PATHWAY_NETWORK
		PATHWAY_NETWORK_C_COMPONENTS
		PATHWAY_NETWORK_IMG_PATHWAYS
		PATHWAY_NETWORK_PARENTS
		PATHWAY_NETWORK_PARTS_LISTS
		PATHWAY_NETWORK_T_COMPONENTS
		PATHWAY_NETWORK_TAXONS
		PFAM_CLAN
		PFAM_CLAN_PFAM_FAMILIES
		PFAM_FAMILY
		PFAM_FAMILY_COGS
		PFAM_FAMILY_EXT_LINKS
		PFAM_FAMILY_FAMILIES
		PFAM_FAMILY_GENOME_PROPERTIES
		PHENOTYPE_RULE
		PHENOTYPE_RULE_TAXONS
		PROJECT_INFO
		PROJECT_INFO_BODY_SITES
		PROJECT_INFO_DATA_LINKS
		PROJECT_INFO_DISEASES
		PROJECT_INFO_ECOTYPES
		PROJECT_INFO_GOLD
		PROJECT_INFO_PHENOTYPES
		PROJECT_INFO_PROJECT_RELEVANCE
		PROJECT_INFO_RELEVANCES
		PROPERTY_STEP
		PROPERTY_STEP_EVIDENCES
		PUBLIC_SET
		REACTION
		REACTION_COMPOUNDS
		REACTION_ENZYMES
		REACTION_EXT_LINKS
		RNASEQ_DATASET
		RNASEQ_DATASET_STATS
		RNASEQ_EXPERIMENT
		RNASEQ_EXPERIMENT_EXT_LINKS
		RNASEQ_EXPERIMENT_PUBS
		RNASEQ_EXPERIMENT_SOP
		RNASEQ_EXPERIMENT_STATS
		RNASEQ_EXPRESSION
		RNASEQ_EXPRESSION_NEW
		RNASEQ_SAMPLE
		RNASEQ_SAMPLE_EXT_LINKS
		RNASEQ_SAMPLE_SOP
		SEED_FUNCTIONAL_ROLE
		STATUSCV
		SUBMISSION
		SUBMISSION_DATA_FILES
		SUBMISSION_IMG_CONTACTS
		SUBMISSION_SAMPLES
		SUBMISSION_STATUSCV
		TAXON_COG_COUNT
		TAXON_EC_COUNT
		TAXON_KO_COUNT
		TAXON_PFAM_COUNT
		TAXON_TIGR_COUNT
		TAXON_UPDATE_REQUEST
		TC_FAMILY
		TC_FAMILY_COGS
		TC_FAMILY_GO_TERMS
		TC_FAMILY_IMG_TERMS
		TC_FAMILY_PFAMS
		TC_FAMILY_PFAMS_IAIN
		TC_FAMILY_TFAMS
		TIGR_ROLE
		TIGRFAM
		TIGRFAM_ENZYMES
		TIGRFAM_GENOME_PROPERTIES
		TIGRFAM_ROLES

	) ];

}

sub img_sat_tables {

	return [ qw(
		BIOCYC_CLASS
		BIOCYC_CLASS_PARENTS
		BIOCYC_CLASS_SYNONYMS
		BIOCYC_CLASS_TYPES
		BIOCYC_COMP
		BIOCYC_COMP_EXT_LINKS
		BIOCYC_COMP_SYNONYMS
		BIOCYC_COMP_TYPES
		BIOCYC_ENZRXN
		BIOCYC_ENZRXN_EXT_LINKS
		BIOCYC_ENZRXN_PROSTH_GROUPS
		BIOCYC_ENZRXN_SYNONYMS
		BIOCYC_PATHWAY
		BIOCYC_PATHWAY_COMMENTS
		BIOCYC_PATHWAY_EXT_LINKS
		BIOCYC_PATHWAY_IN_SPECIES
		BIOCYC_PATHWAY_PWY_LINKS
		BIOCYC_PATHWAY_SUB_PWYS
		BIOCYC_PATHWAY_SUPER_PWYS
		BIOCYC_PATHWAY_TAXON_RANGE
		BIOCYC_PATHWAY_TYPES
		BIOCYC_PROTEIN
		BIOCYC_PROTEIN_CATALYZES
		BIOCYC_PROTEIN_EXT_LINKS
		BIOCYC_PROTEIN_IN_SPECIES
		BIOCYC_PROTEIN_SYNONYMS
		BIOCYC_PROTEIN_TYPES
		BIOCYC_REACTION
		BIOCYC_REACTION_EXT_LINKS
		BIOCYC_REACTION_IN_PWYS
		BIOCYC_REACTION_LEFT_HAND
		BIOCYC_REACTION_RIGHT_HAND
		BIOCYC_REACTION_SYNONYMS
		BIOCYC_REACTION_TYPES
		COG
		COG_FAMILIES
		COG_FUNCTION
		COG_FUNCTION_OBS
		COG_FUNCTIONS
		COG_FUNCTIONS_OBS
		COG_OBS
		COG_PATHWAY
		COG_PATHWAY_COG_MEMBERS
		COG_SPECIES
		COG2014
		COGFUNC2014
		COMPOUND
		COMPOUND_ALIASES
		COMPOUND_EXT_LINKS
		DB_SOURCE
		DT_KO_EC_COG_PFAM
		EGGNOG_HIERARCHY
		EGGNOG_MD52ID2ONT
		ENZYME
		ENZYME_ENZ_ALIASES
		ENZYME_EXT_LINKS
		ENZYME_PRODUCTS
		ENZYME_SUBSTRATES
		GENOME_PROPERTY
		GENOME_PROPERTY_PARENTS
		GO_GRAPH_PATH
		GO_TERM
		GO_TERM_PARENTS
		GO_TERM_SYNONYMS
		IMAGE_ROI
		IMAGE_ROI_COMPOUNDS
		IMAGE_ROI_ENZYMES
		IMAGE_ROI_KO_TERMS
		IMAGE_ROI_REACTIONS
		IMG_BUILD_HISTORY
		INTERPRO
		INTERPRO_GO_TERMS
		KEGG_GENE
		KEGG_GENE_KO_TERMS
		KEGG_GENE_NCBI_GENE_IDS
		KEGG_GENE_NCBI_GI_NUMS
		KEGG_GENE_UNIPROT_IDS
		KEGG_MODULE
		KEGG_MODULE_COMPOUNDS
		KEGG_MODULE_KO_TERMS
		KEGG_MODULE_REACTIONS
		KEGG_PATHWAY
		KEGG_PATHWAY_MODULES
		KEGG_PATHWAY_RELATED_PATHWAYS
		KM_IMAGE_ROI
		KM_IMAGE_ROI_KO_TERMS
		KO_TERM
		KO_TERM_CLASSES
		KO_TERM_COGS
		KO_TERM_ENZYMES
		KO_TERM_GO_IDS
		KO_TERM_MODULES
		KO_TERM_PATHWAYS
		KO_TERM_REACTIONS
		KO_TERM_TC_FAMILIES
		KOG
		KOG_FAMILIES
		KOG_FUNCTION
		KOG_FUNCTIONS
		KOG_PATHWAY
		KOG_PATHWAY_KOG_MEMBERS
		MPW_PGL_COMPOUND
		MPW_PGL_GENE_GROUP
		MPW_PGL_PATHWAY
		MPW_PGL_PATHWAY_REACTION
		MPW_PGL_PROTEIN_GROUP
		MPW_PGL_REACTION
		MPW_PGL_REACTION_COMPOUNDS
		MPW_PGL_TAXONOMY
		PFAM_CLAN
		PFAM_CLAN_PFAM_FAMILIES
		PFAM_FAMILY
		PFAM_FAMILY_COGS
		PFAM_FAMILY_EXT_LINKS
		PFAM_FAMILY_FAMILIES
		PFAM_FAMILY_GENOME_PROPERTIES
		PFAM_FAMILY_V28
		PROPERTY_STEP
		PROPERTY_STEP_EVIDENCES
		REACTION
		REACTION_COMPOUNDS
		REACTION_ENZYMES
		REACTION_EXT_LINKS
		SEED_FUNCTIONAL_ROLE
		TC_FAMILY
		TC_FAMILY_COGS
		TC_FAMILY_GO_TERMS
		TC_FAMILY_IMG_TERMS
		TC_FAMILY_PFAMS
		TC_FAMILY_PFAMS_IAIN
		TC_FAMILY_TFAMS
		TIGR_ROLE
		TIGRFAM
		TIGRFAM_ENZYMES
		TIGRFAM_GENOME_PROPERTIES
		TIGRFAM_ROLES
		YESNOCV
	) ];
}

sub gold_tables {

	return [ qw(
		ANALYSIS_PROJECT_PERMISSIONS
		ANNOUNCEMENT
		ASSEMBLY
		AVAILABILITYCV
		BAD_DEPTH_FILE_WARNINGS
		BATCH
		BEI_STATUSCV
		BIN_METHODCV
		BIOPROJECT_PROPAGATION
		BIOPROJECT_RELEVANCECV
		BIOSAMPLE
		BIOSAMPLE_ATTRIBUTE
		BODY_PRODUCTCV
		BODY_SITECV
		BODY_SUBSITECV
		CANCELLED_USER
		CAPTURECV
		CELL_ARRCV
		CELL_SHAPECV
		COLLABORATORCV
		COLORCV
		CONTACT
		CONTACT_IMG_GROUPS
		CONTACT_JGI_ACCOUNTS
		CONTACT_PROJECT_PERMISSIONS
		CONTACT_SAMPLE_PERMISSIONS
		CONTACT_WORKSPACE_GROUP
		COUNTRY_LOAD
		COUNTRYCV
		CV_COMMUNITY
		CVCULTURE_TYPE
		CVDATA_VALIDITY_TYPE
		CVECOSYSTEM
		CVECOSYSTEM_CATEGORY
		CVECOSYSTEM_SUBTYPE
		CVECOSYSTEM_TYPE
		CVJGI_ITS_FINAL_DELIVERABLE
		CVNATURAL_PRODS
		CVORGANISM_TYPE
		CVPROPAGATION_DATA_TYPE
		CVSPECIFIC_ECOSYSTEM
		CVUNCULTURED_TYPE
		DACC_LOGON
		DATA_QUALITY_FLAGS
		DB_NAMECV
		DISEASECV
		DISEASECV_PARENTS
		DUMMY
		ENERGY_SOURCECV
		ENV_SAMPLE
		ENV_SAMPLE_DATA_LINKS
		ENV_SAMPLE_DISEASES
		ENV_SAMPLE_ENERGY_SOURCE
		ENV_SAMPLE_HABITAT_TYPE
		ENV_SAMPLE_JGI_URL
		ENV_SAMPLE_METABOLISM
		ENV_SAMPLE_MISC_META_DATA
		ENV_SAMPLE_PHENOTYPES
		ENV_SAMPLE_SEQ_METHOD
		ENV_SAMPLE_SOIL_METADATA
		FUNDING_PROGRAMCV
		GENBANK_COMMENT_TEMPLATES
		GENBANK_REFSEQ_CROSSOVER
		GENECALLINGCV
		GOLD_ANALYSIS_PROJECT
		GOLD_ANALYSIS_PROJECT_GENBANKS
		GOLD_ANALYSIS_PROJECT_LOOKUP
		GOLD_ANALYSIS_PROJECT_LOOKUP2
		GOLD_ANALYSIS_PROJECT_USERS
		GOLD_AP_GENBANK
		GOLD_CONTACTCV
		GOLD_IMG_NAT_PROD_ENTITY
		GOLD_SEQUENCING_PROJECT
		GOLD_SP_CELL_ARRANGEMENT
		GOLD_SP_COLLABORATOR
		GOLD_SP_DISEASE
		GOLD_SP_ENERGY_SOURCE
		GOLD_SP_GENOME_PUBLICATIONS
		GOLD_SP_HABITAT
		GOLD_SP_METABOLISM
		GOLD_SP_PHENOTYPE
		GOLD_SP_RELEVANCE
		GOLD_SP_SEQ_CENTER
		GOLD_SP_SEQ_METHOD
		GOLD_SP_STUDY_GOLD_ID
		GOLD_STUDY
		GOLDV5_VIEW
		GTT_FUNC_ID
		GTT_FUNC_ID1
		GTT_FUNC_ID2
		GTT_FUNC_ID3
		GTT_NUM_ID
		GTT_NUM_ID1
		GTT_NUM_ID2
		GTT_NUM_ID3
		HABITAT_CATEGORYCV
		HABITATCV
		HABITATCV_PARENTS
		HMP_PROJECT_STATUSCV
		IMG_GROUP
		IMG_GROUP_NEWS
		IMGCV
		INSTITUTES
		ISOLATE_SUGGESTION_SOURCECV
		JGI_FUNDING_PROGCV
		LANL_PROJECT
		LIBRARY_INFOCV
		LINK_TYPECV
		LOAD_GENBANK_PROK_DATA
		LUSEQ_CENTER
		MASTER_LIST
		MATERIALCV
		MESH_HEADING
		METABOLISMCV
		METAGENOMIC_CLASS_NODES
		METAGENOMIC_CLASS_NODES_NEW
		METAGENOMIC_CLASS_NODES_NEW_BK
		METAGENOMIC_CLASSIFICATION
		METHODCV
		MOTILITYCV
		NCBI_ACCESSIONS
		NCBI_ACCESSIONS_JBTEST
		NCBI_SUBMIT_STATUSCV
		OPROP
		ORA_ASPNET_APPLICATIONS
		ORA_ASPNET_MEMBERSHIP
		ORA_ASPNET_PATHS
		ORA_ASPNET_PERSONALIZNALLUSERS
		ORA_ASPNET_PERSONALIZNPERUSER
		ORA_ASPNET_PROFILE
		ORA_ASPNET_ROLES
		ORA_ASPNET_SESSIONAPPLICATIONS
		ORA_ASPNET_SESSIONS
		ORA_ASPNET_SITEMAP
		ORA_ASPNET_USERS
		ORA_ASPNET_USERSINROLES
		ORA_ASPNET_WEBEVENTS
		ORGANISM_SORT
		ORNL_PROJECT
		OXYGENCV
		PHENOTYPECV
		PHENOTYPECV_PARENTS
		PHYLOGENYCV
		PIG_GENBANK_EMAILED_ACCS
		PIG_RERUNS
		PIG_RETRACTIONS
		PIG_TRACKS
		PLAN_TABLE
		PLAN_TABLE_20131114
		PORTAL_TAXONS
		PROJ_INFO_CELL_ARRANGE_042014
		PROJECT_GOALCV
		PROJECT_INFO
		PROJECT_INFO_04112013
		PROJECT_INFO_BIOPROJECT
		PROJECT_INFO_BIOSAMPLE
		PROJECT_INFO_BODY_PRODUCTS
		PROJECT_INFO_BODY_SITES
		PROJECT_INFO_CELL_ARRANGEMENT
		PROJECT_INFO_COLLABORATORS
		PROJECT_INFO_CYANO_METADATA
		PROJECT_INFO_DATA_LINKS
		PROJECT_INFO_DATA_LINKS_112013
		PROJECT_INFO_DISEASES
		PROJECT_INFO_ENERGY_SOURCE
		PROJECT_INFO_GENBANK
		PROJECT_INFO_GENBANK_AUTHORS
		PROJECT_INFO_GENBANK_COMMENTS
		PROJECT_INFO_HABITAT
		PROJECT_INFO_JGI_URL
		PROJECT_INFO_METABOLISM
		PROJECT_INFO_NATURAL_PRODS
		PROJECT_INFO_NITROGEN_FIXATION
		PROJECT_INFO_NPRODS_METADATA
		PROJECT_INFO_PHENOTYPES
		PROJECT_INFO_PROJECT_RELEVANCE
		PROJECT_INFO_SEQ_METHOD
		PROJECT_META_UPDATES
		PROJECT_STATUSCV
		PROJECT_TYPECV
		PUBLIC_WORKSPACE
		PUBLICATION_JOURNALCV
		PUBLICATION_STATUSCV
		RELEVANCECV
		RELEVANCECV_PARENTS
		REQUEST_ACCOUNT
		REQUEST_STATUSCV
		SALINITYCV
		SAMPLE_SCOPECV
		SAMPLE_TYPECV
		SCHEMA_MIGRATIONS
		SCI_PROGCV
		SEQ_CENTERCV
		SEQ_METHODCV
		SEQ_QUALITYCV
		SEQ_STATUSCV
		SPORULATIONCV
		STUDY
		STUDY_LOAD
		SUBMISSION
		SUBMISSION_DATA_FILES
		SUBMISSION_HISTORY
		SUBMISSION_IMG_CONTACTS
		SUBMISSION_PROC_STATS
		SUBMISSION_PROC_STEPS
		SUBMISSION_READS_FILE
		SUBMISSION_SAMPLES
		SUBMISSION_STATUSCV
		SUBTEST
		T_ALEX_TEST
		T_ALL_GOLD_JGI_PROJECTS
		T_INSTITUTES_BAK
		T_JGI_CATALOGUE
		T_REDDY_TEST
		T1
		T1_AUDIT
		TEMP_RANGECV
		UNITCV
		WEB_PAGE_CODECV
		WEBPAGECV
		WORKSCOPECV
		X_PROJECT_INFO_NP
		YESNOCV
		YESNOONLYCV
	) ];

}
